### ISSUE TITLE
Offer option to display without Card Description

### ISSUE THREAD

**Issue by bluedoors** [Jopyth/MMM-Trello#8]
Would be good to also offer an option for displaying a card title only - ie without the description field. Some descriptions can be quite long making display odd

**Comment by nahtnam** [comment]
Would like to see this as well.

**Comment by O5ten** [comment]
Added a pull-request for this, as it is a very simple fix https://github.com/Jopyth/MMM-Trello/pull/13. 

Feel free to clone my fork if you want the feature before that. 
https://github.com/O5ten/MMM-Trello
